server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver

oss:
  appKey: 1
  appSecret: 1
  bucket: lvgq
  endPoint: https://www.aliyun.com